### ISSUE TITLE
Error while deployment

### ISSUE THREAD

**Issue by sid8840** [khoben/telemirror#108]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 500, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/app/dependencies/telethon/client/telegrambaseclient.py", line 544, in connect
    if not await self._sender.connect(self._connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/dependencies/telethon/network/mtprotosender.py", line 132, in connect
    await self._connect()
  File "/app/dependencies/telethon/network/mtprotosender.py", line 232, in _connect
    connected = await self._try_connect(attempt)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/dependencies/telethon/network/mtprotosender.py", line 282, in _try_connect
    await self._connection.connect(timeout=self._connect_timeout)
  File "/app/dependencies/telethon/network/connection/connection.py", line 244, in connect
    await self._connect(timeout=timeout, ssl=ssl)
  File "/app/dependencies/telethon/network/connection/connection.py", line 216, in _connect
    self._reader, self._writer = await asyncio.wait_for(
                                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 476, in wait_for
    await waiter
asyncio.exceptions.CancelledError
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/app/telemirror/mirroring.py", line 504, in __connect_client
    await asyncio.wait_for(client.connect(), timeout=client._timeout)
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 502, in wait_for
    raise exceptions.TimeoutError() from exc

TimeoutError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/main.py", line 105, in <module>
    main()
  File "/app/main.py", line 91, in main
    asyncio.run(
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/app/main.py", line 66, in run_telemirror
    await telemirror.run()
  File "/app/telemirror/mirroring.py", line 581, in run
    await self._mirroring.run()
  File "/app/telemirror/mirroring.py", line 480, in run
    await self.__connect_client(self._sender)
  File "/app/telemirror/mirroring.py", line 506, in __connect_client
    raise RuntimeError(
RuntimeError: Timeout error while connecting to Telegram server, try restart or get a new session key (run login.py)

**Comment by khoben** [comment]
The error message says it all. This is a network timeout error occurs while connecting to telegram servers. Check for availability of connection to telegram servers and try to restart

**Comment by sid8840** [comment]
I have restarted. it was deployed on Synology Nas. also generated login sessions to rectify but same message.

**Comment by khoben** [comment]
It's definitely a connection issue, Telegram doesn't want to respond to the connection request for some reason

**Comment by sid8840** [comment]
I am able to solve it by modifying firewall settings in Synology, thanks.
any plans for web based Gui for this excellent program so that options like message filters can filled online.

**Comment by khoben** [comment]
> I am able to solve it by modifying firewall settings in Synology, thanks.
> any plans for web based Gui for this excellent program so that options like message filters can filled online.
> 

There are no plans for web UI in the near future. Maybe someone interested in this will create a pull request with implementation.
